services:
  api:
    container_name: proxy
    build: .
    command: node dist/main
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - 3001:3000
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
